server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # Auth service route
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
          # Example:
          # Gateway -> http://localhost:4004/auth/login
          # Actual service -> http://auth-service:4005/login

        # Patient service route
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Patient API docs route
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # Auth  API docs route
        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

          # Example:
          # Rest client -> http://localhost:4004/api-docs/patients
          # Gateway -> http://patient-service:4000/v3/api-docs
