### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "darsha tugudeepa",
  "email": "jalagara@example.com",
  "address": "ballaryJail",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###