### PUT to update patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "ajja Soonti",
  "email": "teats_updated@example.com",
  "address": "456 main street",
  "dateOfBirth": "1923-09-09"
}

###